#!/bin/bash

options=(
  style=round
  width=5
  hidpi=on
  order=above

  # --- BRIGHT NEON BLUE GRADIENT ---
  # Top Left: Vibrant Electric Cyan Blue
  # Bottom Right: Your favorite Neon Mint Blue
  active_color="gradient(top_left=0xff00d5ff,bottom_right=0xff00ffaa)"
  inactive_color="0x00ffffff"

  # --- FIREFOX FLICKER FIX ---
  blacklist="Firefox"
)

borders "${options[@]}"
