font_family      CaskaydiaCove Nerd Font
# kitty defaults to 11
font_size        13.0
modify_font      cell_height 135%

background_opacity 0.8
background_blur    20

macos_option_as_alt yes


# BEGIN_KITTY_THEME
# Gruvbox Dark Hard
include current-theme.conf
# END_KITTY_THEME

# Catppuccin Mantle, one step darker than Mocha's default background
# Must stay below the theme block to override it
#background #181825
